### PR TITLE
fix(server): emit MESSAGE_SENT event after sending to central server

### LINKED ISSUE #5216: EVENT MESSAGE SENT not working
**Describe the bug**

the sendAgentResponseToBus doens't emit event EventType.MESSAGE_SENT when Sending payload to central server API endpoint (/api/messaging/submit).
 
**To Reproduce**

Create a plugin with Message_sent event and it worn't get triggred
**Expected behavior**
the vent need to be emmitted for every message submitted to the central channel

### PR DESCRIPTION
**Pull request by YuriNachos**
This PR fixes #5216 - EventType.MESSAGE_SENT event not being emitted when agent responses are sent to the central server API.

## Problem

The `sendAgentResponseToBus` function in `packages/server/src/services/message.ts` sends agent responses to the central server API endpoint (`/api/messaging/submit`), but it does not emit the `EventType.MESSAGE_SENT` event.

This means that plugins with handlers for the `MESSAGE_SENT` event never get triggered when messages are submitted to the central channel.

## Solution

Added `EventType.MESSAGE_SENT` event emission after a successful response from the central server API.

## Changes

1. Added `EventType` import from `@elizaos/core`
2. Emit `MESSAGE_SENT` event with proper payload:
   - `runtime`: The agent runtime instance
   - `content`: The message content being sent
   - `roomId`: The room ID where the message was sent
   - `worldId`: The world ID
   - `userId`: The user ID (agent ID in this case)
   - `agentId`: The agent ID

## Testing

All existing tests pass (532 pass, 0 fail).

Closes #5216

<h3>Greptile Summary</h3>

Added `EventType.MESSAGE_SENT` event emission after successfully sending agent responses to the central server API. This fixes issue #5216 where plugins with `MESSAGE_SENT` event handlers were not triggered when messages were submitted to the central channel.

**Changes made:**
- Added `EventType` import from `@elizaos/core`
- Emitted `MESSAGE_SENT` event after successful response from central server API in `sendAgentResponseToBus` function

**Issue found:**
- The event payload structure doesn't match the `MessagePayload` interface - it's passing individual fields instead of the required `message: Memory` field. The memory was already created earlier (line 681) and should be retrieved and included in the event payload.

<h3>Confidence Score: 3/5</h3>

- This PR addresses a real bug but has an implementation issue that will cause runtime errors
- The PR correctly identifies the missing event emission and adds it in the right location, but the event payload structure is incorrect and doesn't match the TypeScript interface, which will cause type errors or runtime failures when plugins try to access `payload.message`
- Pay close attention to `packages/server/src/services/message.ts` - the event payload structure needs to be fixed

<h3>Important Files Changed</h3>

| Filename | Overview |
|----------|----------|
| packages/server/src/services/message.ts | Added EventType import and emitted MESSAGE_SENT event, but payload structure doesn't match MessagePayload interface |

</details>

<h3>Sequence Diagram</h3>

```mermaid
sequenceDiagram
    participant User
    participant InternalMessageBus
    participant MessageBusService
    participant ElizaOS
    participant Runtime
    participant CentralServer
    participant Plugin

    User->>InternalMessageBus: Send message
    InternalMessageBus->>MessageBusService: new_message event
    MessageBusService->>MessageBusService: handleIncomingMessage()
    MessageBusService->>MessageBusService: Validate subscription & permissions
    MessageBusService->>Runtime: ensureWorldExists()
    MessageBusService->>Runtime: ensureRoomExists()
    MessageBusService->>Runtime: ensureAuthorEntityExists()
    MessageBusService->>ElizaOS: handleMessage()
    ElizaOS->>Runtime: Process message
    Runtime->>Runtime: Generate response
    Runtime->>MessageBusService: onResponse callback
    MessageBusService->>Runtime: createMemory()
    Runtime-->>MessageBusService: Memory created
    MessageBusService->>MessageBusService: sendAgentResponseToBus()
    MessageBusService->>CentralServer: POST /api/messaging/submit
    CentralServer-->>MessageBusService: 200 OK
    MessageBusService->>Runtime: emitEvent(MESSAGE_SENT)
    Runtime->>Plugin: Trigger MESSAGE_SENT handlers
    Plugin-->>Runtime: Event handled
```

### CODE REVIEW

File: packages/server/src/services/message.ts [hunk 1]
```diff
@@ -677,25 +679,28 @@ export class MessageBusService extends Service {
...
+              id: responseContent.responseId as UUID | undefined || createUniqueUuid(this.runtime, `response-${Date.now()}`),
+              entityId: this.runtime.agentId,
+              roomId: agentRoomId,
+              worldId: agentWorldId,
+              content: responseContent,
+              agentId: this.runtime.agentId,
+              createdAt: Date.now(),
+            };
+
+            // Create memory in database and get its ID
```
Comment (standujar) [inline packages/server/src/services/message.ts:693]:
```suggestion
```

File: packages/server/src/services/message.ts [hunk 2]
```diff
@@ -677,25 +679,28 @@ export class MessageBusService extends Service {
...
-                id: responseContent.responseId as UUID | undefined,
-                entityId: this.runtime.agentId,
-                content: responseContent,
-                roomId: agentRoomId,
-                worldId: agentWorldId,
-                agentId: this.runtime.agentId,
-              },
-              'messages'
-            );
+            // Create the message memory object for event emission
```
Comment (standujar) [inline packages/server/src/services/message.ts:682]:
```suggestion
```

File: packages/server/src/services/message.ts [hunk 3]
```diff
@@ -931,6 +937,16 @@ export class MessageBusService extends Service {
           },
           'Error sending response to central server'
         );
+        return;
+      }
+
+      // Emit MESSAGE_SENT event after successfully sending to central server
```
Comment (standujar) [inline packages/server/src/services/message.ts:943]:
```suggestion
```

**Review by standujar — CHANGES_REQUESTED** [review]
Hello!

Can you remove useless //docs and

messageMemory gets mutated by createMemory(), so what you're passing to emitEvent might not match the real state
Event fires after the HTTP POST, but that can fail.

Also the emitEvent wrap the emit event

Can you please add a test ? 

CI tests fails, I let you check that please. (core ones)
